### ISSUE TITLE
Add image metrics tool to help with blob extraction 

### ISSUE THREAD

**Issue by jrbourbeau** [WIPACrepo/decotools#39]
It would be nice to have a function that takes an image path and returns several metrics to help us determine if it is a "good" image that we should pass to `decotools.extract_blobs`. 

Metrics I can think of:

1. Average pixel intensity (over the entire image) &mdash; this can help filter out super noisy images 
2. Maximum pixel intensity (over the entire image)
3. Number of pixels above a specified intensity threshold.

@mattmeehan @cschneider6 @milesjwinter any other potential metrics you can think of?

**Comment by milesjwinter** [comment]
@jrbourbeau I think these metrics are pretty good. Instead of/in addition to the average intensity, we may find that percentiles are more useful. Maybe we calculate the 16th, 50, and 84th percentiles. This might give us a better idea about whether or not the entire image is noisy or just some really bright local region.

**Comment by mattmeehan** [comment]
@jrbourbeau @milesjwinter I like those ideas. I think the combination of those metrics should enable us to easily filter out noisy images, especially on a larger scale. The remaining difficult case will be images that have localized noise similar in size to actual events, but the CNN should be able to accurately classify these.

**Comment by jrbourbeau** [comment]
Great, thanks for the comments! Adding the percentiles is definitely the way to go. I'll work on a PR for this.
